Added poetry

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -25,13 +25,13 @@ jobs:
         with:
           python-version: ${{ env.PYTHON_VERSION }}
 
-      - name: Install black
+      - name: Setup poetry
         run: |
-          pip install --upgrade pip
-          pip install black
+          pip install poetry poethepoet
+          poetry install -n --no-root
 
       - name: Check code formatting with black
-        run: black -l 120 . --diff --check
+        run: poe black --diff --check
 
   mypy:
     if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository }}
@@ -48,14 +48,13 @@ jobs:
         with:
           python-version: ${{ env.PYTHON_VERSION }}
 
-      - name: Install mypy
+      - name: Setup poetry
         run: |
-          pip install --upgrade pip
-          pip install -r requirements.txt
-          pip install mypy types-python-dateutil types-requests
+          pip install poetry poethepoet
+          poetry install -n --no-root
 
       - name: Check typing with mypy
-        run: mypy PyCrypCli
+        run: poe mypy
 
   linter:
     runs-on: ubuntu-latest
@@ -71,13 +70,13 @@ jobs:
         with:
           python-version: ${{ env.PYTHON_VERSION }}
 
-      - name: Install wemake-python-styleguide
+      - name: Setup poetry
         run: |
-          pip install --upgrade pip
-          pip install wemake-python-styleguide bandit==1.7.2
+          pip install poetry poethepoet
+          poetry install -n --no-root
 
       - name: Check code style with wemake-python-styleguide
-        run: flake8 PyCrypCli --count --statistics --show-source
+        run: poe flake8
 
 #      - name: Lint with wemake-python-styleguide
 #        uses: wemake-services/wemake-python-styleguide@0.16.0
@@ -98,36 +97,29 @@ jobs:
           submodules: recursive
           fetch-depth: 0
 
+      - name: Check Version
+        run: |
+          if [[ $GITHUB_REF = refs/tags/v* ]]; then
+            tag=${GITHUB_REF#refs/tags/v}
+            version=$(grep '^version =' pyproject.toml | cut -d'"' -f2)
+            if [[ "$tag" != "$version" ]]; then
+              echo "::error::Tag $tag does not match version $version"
+              exit 1
+            fi
+          fi
+
       - name: Set up Python ${{ env.PYTHON_VERSION }}
         uses: actions/setup-python@v3
         with:
           python-version: ${{ env.PYTHON_VERSION }}
 
-      - name: Install build dependencies
+      - name: Setup poetry
         run: |
-          pip install --upgrade pip
-          pip install wheel
-
-      - name: Create Version
-        id: version
-        run: |
-          set -x
-
-          tag=${GITHUB_REF#refs/tags/v}
-
-          if [[ $GITHUB_REF = refs/tags/v* ]]; then
-            version="v$tag"
-          elif [[ $GITHUB_REF = refs/heads/* ]]; then
-            version=$(git describe --tags | sed 's/-/+/')
-          fi
-          version="$(echo $version | tr / -)"
-
-          echo ::set-output name=version::${version}
+          pip install poetry
+          poetry install -n --no-root
 
       - name: Build python package
-        env:
-          VERSION: ${{ steps.version.outputs.version }}
-        run: python setup.py sdist bdist_wheel
+        run: poetry build
 
       - name: Upload dist
         uses: actions/upload-artifact@v2
@@ -255,9 +247,7 @@ jobs:
           path: dist
 
       - name: Install Twine
-        run: |
-          pip install --upgrade pip
-          pip install twine
+        run: pip install twine
 
       - name: Upload package to PyPi
         run: python -m twine upload -u __token__ -p ${{ secrets.PYPI_TOKEN }} dist/*
